clickable links and "manage"was spelled wrong
zjunior-infra/Dashboard pull request #24
Opened 2023-05-08 14:47 UTC by loaai-rashad

in the read me file the MySQL URL should have ":" instead of "@" so the database was not being runned 
changed the spelling of "mnage" to "manage"
made the link clickable and underlined when hoverover it

2023-05-08 15:54 UTC, Mahmoudgalalz commented on prisma/.env
> +MAIN_DATABASE_URL="mysql://user:password@localhost:3306/db"
you should add this file to .gitignore
so create one and add this file and push the commits to the pr
don't forget to rm this file from the git stage

2023-05-08 15:56 UTC, Mahmoudgalalz commented on README.md
> +your connection string will be `mysql://admin:password@localhost:3306/db`
does admin work ? not user
#23 this issue related to this and he cleared that the user is `user`

2023-05-08 15:56 UTC, Mahmoudgalalz commented on components/DataGrid.tsx
@EL-Gazoly waiting for ur review, I approve it what about you

2023-05-08 15:56 UTC, Mahmoudgalalz requested changes
Do the changes on the same PR

2023-05-09 14:12 UTC, EL-Gazoly commented on components/DataGrid.tsx
I approve it surly. Great job Loai

2023-05-09 15:38 UTC, Mahmoudgalalz commented on components/DataGrid.tsx
Thanks @loaai-rashad, do the other changes and this would be ur first contribution to zJunior

2023-05-09 15:40 UTC, Mahmoudgalalz commented
this close #23 and close #22

2023-05-09 15:40 UTC, merged