Rebuilding the Dashboard initial commit
zjunior-infra/Dashboard pull request #44
Opened 2023-08-30 04:58 UTC by Ahmed-Elhalwagy

2023-08-31 01:46 UTC, Mahmoudgalalz requested changes
The table is shaking, with no resone, also non of the functions works at all, and cannot delete, update 

and I cannot confirm, there's no selection

let me know if you are working on these

There's types error

2023-08-31 02:53 UTC, Ahmed-Elhalwagy commented
I am working on these existing problems

2023-09-05 22:46 UTC, Mahmoudgalalz commented on components/DataTable.tsx
> +  id:'123123',
Remove the bulk data

2023-09-05 22:46 UTC, Mahmoudgalalz commented on components/DataTable.tsx
> +  console.log('Save Done');
Waiting for the #49

2023-09-05 22:47 UTC, Mahmoudgalalz commented on components/DataTable.tsx
> +              const target = e.target as HTMLElement;
Specify the type of the Element

2023-09-05 22:51 UTC, Mahmoudgalalz commented on components/TableButtons.tsx
> +  const newJob= {
You add a plain job, I want to send data from the dashboard that I create

2023-09-05 22:58 UTC, Mahmoudgalalz requested changes
I asked for some changes, and there's change's
I wanted to fix the adding feature, I don't why you have implemented with this way, there's a way to add a row within the table then once it's new row and we click on the save button it will save, not update it

also we need a button to confirm the job, within the action buttons

2023-09-18 00:20 UTC, merged